export const SECURITY_CONFIG = {
    ALLOWED_ORIGINS: [''],
    ALLOWED_METHODS: ['GET', 'POST', 'PATCH', 'HEAD', 'DELETE', 'OPTIONS'],
    ALLOWED_HEADERS: [
        'Content-Type',
        'Upload-Length',
        'Upload-Metadata',
        'Upload-Offset',
        'Upload-Defer-Length',
        'Upload-Checksum',
        'Upload-Concat',
        'Upload-Expires',
        'Tus-Resumable',
        'Tus-Version',
        'Tus-Extension',
        'Tus-Max-Size',
        'Tus-Checksum-Algorithm',
        'Tus-Checksum-Value',
        'Authorization',
        'X-Http-Method-Override',
        'Accept',
        'Accept-Encoding',
        'Cache-Control',
        'Vary',
        'WWW-Authenticate',
        'CF-Connecting-IP',
        'X-Health-Check',
        'X-Response-Time',
        'User-Agent',
        'X-Cloudflare-Cron',
        'Location',
        'X-RateLimit-Limit',
        'X-RateLimit-Remaining',
        'X-RateLimit-Reset',
    ],
    EXPOSE_HEADERS: [
        'Location',
        'Upload-Offset',
        'Upload-Length',
        'Upload-Checksum',
        'Upload-Expires',
        'Upload-Defer-Length',
        'Upload-Concat',
        'Upload-Metadata',
        'Tus-Resumable',
        'Tus-Version',
        'Tus-Extension',
        'Tus-Max-Size',
        'Tus-Checksum-Algorithm',
        'Tus-Checksum-Value',
        'Cache-Control',
        'Vary',
        'X-RateLimit-Limit',
        'X-RateLimit-Remaining',
        'X-RateLimit-Reset',
        'WWW-Authenticate',
        'CF-Connecting-IP',
        'X-Health-Check',
        'X-Response-Time',
        'User-Agent',
        'X-Cloudflare-Cron',
        'Location',
    ],
    CREDENTIALS: true,
};
